version: '3.7'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      SA_PASSWORD: "password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
      #- ./data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: alessandro
      ME_CONFIG_MONGODB_ADMINPASSWORD: Teste123!
    depends_on:
      - mongo